name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Instrument code
      uses: AryazE/auto-dylin/instrument@main

    - name: Run tests
      run: |
        pytest test.py
    
    - name: Log 2
      run: |
        ls
        cat test.py
        ls /tmp/dynapyt_*-${{ env.DYNAPYT_SESSION_ID }}
    
    - name: DyLin reports
      if: always()
      uses: AryazE/auto-dylin/report@main